[build]
  command = "npm run generate"
  publish = "dist"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=8192"

[[redirects]]
  from = "https://eduardomecchia.com"
  to = "https://eduardomecchiafernandez.com"
  status = 301
  force = true